django_proj/accounts/urls.py
from django.urls import path
from django_proj.urls import account_app_name
from django.contrib.auth import views as auth_views
from accounts import views as acv

app_name = account_app_name

urlpatterns = [
    path('', acv.home, name='home'),
    path('/update', acv.UserUpdateView.as_view(), name='update'),
    path('/profile/', acv.profile, name='profile'),
    path('/signup', acv.signup, name='signup'),
    path('/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('/logout', auth_views.LogoutView.as_view(), name='logout'),
 
]

django_proj/django_proj/urls.py
from django.contrib import admin
from django.urls import path, include

# from djpolls import views
from djpolls.apps import DjpollsConfig
from accounts.apps import AccountsConfig

from django.conf.urls import url
from django.contrib import admin # authentication system
from django.contrib.auth import views as auth_views # authentication system
from djpolls import views
from rest_framework import routers

djpolls_app_name = DjpollsConfig.name # follow here: https://stackoverflow.com/a/56054638/5027340
account_app_name = AccountsConfig.name

router = routers.DefaultRouter()
router.register(r'question', views.QuestionViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path(djpolls_app_name, include('djpolls.urls', namespace='djpolls_app_name')),
    path(account_app_name, include('accounts.urls', namespace='account_app_name')),
    # path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    path('', include('djpolls.urls')),
    # or
    # path('', views.home),
]

django_proj/djpolls/urls.py
from django.urls import path
from djpolls import views as djpviews
from django_proj.urls import djpolls_app_name

app_name = djpolls_app_name

urlpatterns = [
    path('', djpviews.home, name='home'),
    path('/<int:question_id>/', djpviews.detail, name='detail'),
    path('/<int:question_id>/vote/', djpviews.vote, name='vote'),
    path('/<int:question_id>/result/', djpviews.results, name='results'),
    
]

django_proj/accounts/models.py
from django.db import models

# Create your models here.

django_proj/djpolls/models.py
from django.db import models

# Create your models here.
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Question (models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Answer (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)    

    def __str__(self):
        return self.choice_text

django_proj/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email')

django_proj/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse, Http404
from django.urls import reverse_lazy
from django.template import loader
from django.views.generic import UpdateView
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import SignUpForm
from django.contrib.auth.models import User
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator

def home(request):
    return render(request, 'accounts/account.html')

# def logout(request):
#     return render(request, 'accounts/account.html')

def profile(request):
    return redirect('/accounts')

def signup(request):
    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            messages.success(request, f'Account {user.username} is created and logged in, Enjoy!')
            return redirect('/accounts')
        #else:
            #return HttpResponse('Loi cmnr')
            # return redirect('/accounts')
    else:
        form = SignUpForm()
        # form = UserCreationForm()
        
    return render(request, 'accounts/signup.html', {'form': form})

class UserUpdateView(UpdateView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'date_joined' )
    template_name = 'accounts/update.html'
    success_url = reverse_lazy('accounts:update')

    def get_object(self):
        return self.request.user

django_proj/djpolls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import Question, Answer
from django.utils.translation import ugettext
from .serializers import QuestionSerializer
from rest_framework import viewsets

# def home(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = '<br>'.join([q.question for q in latest_question_list])
#     return HttpResponse(output)

# def home(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('djpolls/home.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:50]
    message = ugettext('Welcome!')
    context = {'latest_question_list': latest_question_list, 'message': message}
    return render(request, 'djpolls/home.html', context)

def login(request):
    return render(request, 'djpolls/login.html')

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        return render(request, 'djpolls/404.html')
    return render(request, 'djpolls/detail.html', {'question': question})

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.answer_set.get(pk=request.POST['choice'])
    except (KeyError, Answer.DoesNotExist):
        return render(request, 'djpolls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('djpolls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'djpolls/result.html', {'question': question})

class QuestionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Question.objects.all().order_by('-pub_date')
    serializer_class = QuestionSerializer

django_proj/accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  {% if not user.is_authenticated %}
    You need to Login first!
    <a href="{% url 'accounts:login' %}">Login</a> |
    <a href="{% url 'accounts:signup' %}">Sign up</a>
  {% else %}
    This is home for Account!
    
  {% endif %}
{% endblock %}

django_proj/accounts/templates/accounts/inc/signup-form.html
 {% for field in form %}
<div class="form-group">

    {% if field.errors %}
    <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
    {% endif %} {{ field.label_tag }} {{ field }} {% if field.help_text %}
    <small class="form-text text-muted">
        {{ field.help_text|safe }}  
      </small> {% endif %}
</div>
{% endfor %}

django_proj/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Login with Django built-in</h3>
            <form method="post" action="{% url 'accounts:login' %}">
              {% csrf_token %}
                {% for field in form %}
                  <div class="form-group">
                    
                    {% if field.errors %}
                      <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
                    {% endif %}
                    {{ field.label_tag }}
                    {{ field }}

                    {% if field.help_text %}
                      <small class="form-text text-muted">
                        {{ field.help_text|safe }}  
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
              <input type="submit" value="login" class="btn btn-primary" />
              <input type="hidden" name="next" value="{{ next }}" />
            </form>
          
          </div>
          <div class="card-footer text-muted text-center">
            <a href="{% url 'accounts:signup' %}">Sign up</a> |
            <a href="{% url 'accounts:login' %}">Login</a>
          </div>
        </div>
      </div>
    </div>
    
    {% comment %} <h3>Login with Django built-in</h3>
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <table>
            <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
            </tr>

            <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
            </tr>
        </table>
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form> {% endcomment %}

{% endblock %}

django_proj/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up - Using Django built-in UserCreationForm!</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'accounts/inc/signup-form.html' %}
              {% comment %} {{ form.as_p }} {% endcomment %}
              <button type="submit" class="btn btn-primary">Create an account</button>
            </form>
          
          </div>
          <div class="card-footer text-muted text-center">
            <a href="{% url 'djpolls:home' %}">Home</a> |
            <a href="{% url 'accounts:login' %}">Login</a>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

django_proj/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  {% if not user.is_authenticated %}
    You need to Login first!
    <a href="{% url 'accounts:login' %}">Login</a> |
    <a href="{% url 'accounts:signup' %}">Sign up</a>
  {% else %}
    Update Account!
    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post" novalidate>
          {% csrf_token %}
          {% include 'accounts/inc/signup-form.html' %}
          <button type="submit" class="btn btn-success">Save changes</button>
        </form>
      </div>
    </div>
  {% endif %}
{% endblock %}

django_proj/djpolls/templates/djpolls/detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ question.question }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'djpolls_app_name:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.answer_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

    <a href="{% url 'djpolls_app_name:home' %}"><- Back</a>

{% endblock %}

django_proj/djpolls/templates/djpolls/home.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ message }}</h1>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'djpolls_app_name:detail' question.id %}">{{ question.question }}</a></li>
            
        {% endfor %}
        </ul>
    {% else %}
        <p>No questions are available.</p>
    {% endif %}

{% endblock %}

django_proj/djpolls/templates/djpolls/result.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ question.question }}</h1>

    <ul>
    {% for choice in question.answer_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'djpolls_app_name:detail' question.id %}"><- Back</a>

{% endblock %}

django_proj/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% trans 'Homepage' %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}  
  </head>
  <body>
    {% block body %} 
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'djpolls:home' %}">Django Demo</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'djpolls:home' %}">DJPolls app</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/admin">Admin</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'accounts:home' %}">My account</a>
                    <a class="dropdown-item" href="{% url 'accounts:update' %}">Update account</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                  </div>
                </li>
              </ul>
            {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <div class="container">
        <ol class="breadcrumb my-4">
          <li class="breadcrumb-item active">Home</li>
          {% block breadcrumb %}
          {% endblock %} 
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %} 
    
    <footer class="container text-center"><hr>
      <p>© 2019 - build with Python Django</p>
    </footer>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>